// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use a dummy URL for generation if DATABASE_URL is not set
    url: process.env["DATABASE_URL"] || "postgresql://user:pass@localhost:5432/db",
  },
});
